### ISSUE TITLE
we chatted on reddit

### ISSUE THREAD

**Issue by OGnoob1** [jorkorschool/pulsepoints#1]
hey man idk if you will get this but we used to chat on reddit my user was @acclimateAdversity. Just wanted to keep in touch with you, hope all is well. My discord is OGnoob #0138 if you want to reach out. Take care

**Comment by jorkorschool** [comment]
hey @OGnoob1 im just seeing this - just tried to add you and it said invalid username haha. feel free to shoot me an email @ jordankorn@me.com

forgive me for not remembering interacting with you
